CONNECT 'jdbc:derby:linedb;create=true';

CREATE TABLE PROFILE (
	PRFE_ID INT NOT NULL PRIMARY KEY,
	PRFE_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE DOCUMENT (
	DOC_ID INT NOT NULL PRIMARY KEY,
	PRFE_EXCP_ID INT,
	PRFE_FULL_ID INT,
	DOC_NUMBER INT NOT NULL,
	CONSTRAINT prfe_excep_id_ref FOREIGN KEY (PRFE_EXCP_ID) REFERENCES PROFILE(PRFE_ID),
	CONSTRAINT prfe_full_id_ref FOREIGN KEY (PRFE_FULL_ID) REFERENCES PROFILE(PRFE_ID)
);

CREATE TABLE LIMIT (
	LMTE_ID INT NOT NULL PRIMARY KEY,
	PRFE_ID INT NOT NULL,
	LMTE_VALUE INT NOT NULL,
	CONSTRAINT prfe_id_ref FOREIGN KEY (PRFE_ID) REFERENCES PROFILE(PRFE_ID)
);

INSERT INTO PROFILE (PRFE_ID, PRFE_NAME) 
	VALUES (0, 'PROFILE-0');

INSERT INTO LIMIT (LMTE_ID, PRFE_ID, LMTE_VALUE)
	VALUES (0, 0, 0);

INSERT INTO DOCUMENT (DOC_ID, PRFE_EXCP_ID, PRFE_FULL_ID, DOC_NUMBER)
	VALUES (0, 0, NULL, 0); 
