CONNECT 'jdbc:derby:testdb;create=true';

CREATE TABLE PROFILE (
	PRFE_ID INT NOT NULL PRIMARY KEY,
	PRFE_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE USER (
	USER_ID INT NOT NULL PRIMARY KEY,
	PRFE_MAIN_ID INT,
	PRFE_PART_ID INT,
	DOC_NUMBER INT NOT NULL,
	CONSTRAINT prfe_main_id_ref FOREIGN KEY (PRFE_MAIN_ID) REFERENCES PROFILE(PRFE_ID),
	CONSTRAINT prfe_part_id_ref FOREIGN KEY (PRFE_PART_ID) REFERENCES PROFILE(PRFE_ID)
);

CREATE TABLE CONFIG (
	CNFE_ID INT NOT NULL PRIMARY KEY,
	PRFE_ID INT NOT NULL,
	CNFE_VALUE INT NOT NULL,
	CONSTRAINT prfe_id_ref FOREIGN KEY (PRFE_ID) REFERENCES PROFILE(PRFE_ID)
);

INSERT INTO PROFILE (PRFE_ID, PRFE_NAME) 
	VALUES (0, 'PROFILE-0');

INSERT INTO CONFIG (CNFE_ID, PRFE_ID, CNFE_VALUE)
	VALUES (0, 0, 0);

INSERT INTO USER (USER_ID, PRFE_MAIN_ID, PRFE_PART_ID, DOC_NUMBER)
	VALUES (0, 0, NULL, 0); 
